# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages via angular-cli-ghpages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Runs on a daily schedule, based on UTC time
  schedule:
    - cron:  '45 9 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Environment
env:
  APP_BASE_HREF:          ${{ format('/{0}/', github.event.repository.name) }}
  REPO_CLONE_URL:         ${{ github.event.repository.clone_url }}
  GIT_KNOWLEDGE_APP_REPO: 'digitalreplica/git-knowledge-app'
  REPO_LIST_PATH:         'repos.txt'
  KNOWLEDGE_JSON_PATH:    'git-knowledge-app/src/assets/knowledge.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  deploy-git-knowledge-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Disabled by default, change to true to enable
      - name: Dump env context
        if: ${{ false }}
        env:
          ENV_CONTEXT: ${{ toJSON(env) }}
        run: echo "$ENV_CONTEXT"
      
      # Check out knowledge repo and git-knowledge-app
      - name: Checkout knowledge repo
        uses: actions/checkout@v2
        
      - name: Checkout git-knowledge-app
        uses: actions/checkout@v2
        with:
          repository: '${{ env.GIT_KNOWLEDGE_APP_REPO }}'
          path: git-knowledge-app
        
      - name: Verify repo list exists
        run: |
          (test -f ${{ env.REPO_LIST_PATH }} && echo "REPO_LIST_EXISTS=true" >> $GITHUB_ENV) || echo "REPO_LIST_EXISTS=false" >> $GITHUB_ENV
      
      - run: echo "${{ env.REPO_LIST_PATH }} exists"
        if: ${{ env.REPO_LIST_EXISTS }}

      # Create knowledge.json
      - name: Create knowledge.json file
        if: ${{ env.REPO_LIST_EXISTS }}
        uses: digitalreplica/git-knowledge-json-action@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          repo-list-path: ${{ env.REPO_LIST_PATH }}
          knowledge-json-path: ${{ env.KNOWLEDGE_JSON_PATH }}
      
      - name: List knowledge.json file
        run: ls -la "${{ env.KNOWLEDGE_JSON_PATH }}"
      
      # Deploy to GitHub pages
      - name: Use Node.js 12
        if: ${{ env.REPO_LIST_EXISTS }}
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        if: ${{ env.REPO_LIST_EXISTS }}
        working-directory: ./git-knowledge-app
        run: npm install

      - name: Deploy to GitHub pages using angular-cli-ghpages
        if: ${{ env.REPO_LIST_EXISTS }}
        working-directory: ./git-knowledge-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ng -- deploy --base-href=$APP_BASE_HREF --repo=$REPO_CLONE_URL --name=github-actions --email=github-actions@github.com
