# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages via angular-cli-ghpages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Environment
env:
  REPO_HREF:            '/git-knowledge-app/'
  REPO_LIST_PATH:       'repos.txt'
  KNOWLEDGE_JSON_PATH:  'src/assets/knowledge.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Verify repo list exists
        run: |
          (test -f ${{ env.REPO_LIST_PATH }} && echo "REPO_LIST_EXISTS=true" >> $GITHUB_ENV) || echo "REPO_LIST_EXISTS=false" >> $GITHUB_ENV
      
      - run: export
      
      - name: Use Node.js 12
        if: ${{ false }}
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        if: ${{ false }}
        run: npm install

      - name: Create knowledge.json file
        if: ${{ false }}
        uses: digitalreplica/git-knowledge-json-action@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          repo-list-path: 'repos.txt'
          knowledge-json-path: 
      
      - name: Deploy to GitHub pages using angular-cli-ghpages
        if: ${{ false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ng -- deploy --base-href='/git-knowledge-app/' --name="deploy-bot" --email=deploybot@digitalreplica.org
